version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

sphinx:
  configuration: docs/conf.py

python:
  install:
    # Install your actual package (THIS IS MISSING RIGHT NOW)
    - method: pip
      path: .
    # Install your documentation dependencies
    - requirements: docs/requirements.txt
