[
    {
        "distance": "1",
        "mask": "32",
        "metric": "0",
        "network": "1.1.1.1",
        "nexthop_if": "",
        "nexthop_ip": "212.0.0.1",
        "nexthop_vrf": "",
        "protocol": "S",
        "type": "",
        "uptime": "",
        "vrf": "",
    },
    {
        "distance": "1",
        "mask": "32",
        "metric": "0",
        "network": "1.1.1.1",
        "nexthop_if": "",
        "nexthop_ip": "192.168.0.1",
        "nexthop_vrf": "",
        "protocol": "S",
        "type": "",
        "uptime": "",
        "vrf": "",
    },
    {
        "distance": "",
        "mask": "24",
        "metric": "",
        "network": "2.2.2.0",
        "nexthop_if": "FastEthernet0/0.100",
        "nexthop_ip": "",
        "nexthop_vrf": "",
        "protocol": "S",
        "type": "",
        "uptime": "",
        "vrf": "",
    },
    {
        "distance": "110",
        "mask": "16",
        "metric": "20",
        "network": "4.4.0.0",
        "nexthop_if": "FastEthernet0/0.100",
        "nexthop_ip": "194.0.0.2",
        "nexthop_vrf": "",
        "protocol": "O",
        "type": "E2",
        "uptime": "1d18h",
        "vrf": "",
    },
    {
        "distance": "170",
        "mask": "24",
        "metric": "2297856",
        "network": "5.5.5.0",
        "nexthop_if": "Serial0/0",
        "nexthop_ip": "10.0.1.2",
        "nexthop_vrf": "",
        "protocol": "D",
        "type": "EX",
        "uptime": "00:12:01",
        "vrf": "",
    },
    {
        "distance": "200",
        "mask": "16",
        "metric": "0",
        "network": "6.6.0.0",
        "nexthop_if": "",
        "nexthop_ip": "195.0.0.1",
        "nexthop_vrf": "",
        "protocol": "B",
        "type": "",
        "uptime": "00:00:04",
        "vrf": "",
    },
    {
        "distance": "115",
        "mask": "26",
        "metric": "10",
        "network": "172.16.1.0",
        "nexthop_if": "Serial0/0",
        "nexthop_ip": "10.0.1.2",
        "nexthop_vrf": "",
        "protocol": "i",
        "type": "L2",
        "uptime": "",
        "vrf": "",
    },
    {
        "distance": "110",
        "mask": "32",
        "metric": "11",
        "network": "172.20.1.1",
        "nexthop_if": "FastEthernet0/0.100",
        "nexthop_ip": "194.0.0.2",
        "nexthop_vrf": "",
        "protocol": "O",
        "type": "",
        "uptime": "00:05:45",
        "vrf": "",
    },
    {
        "distance": "110",
        "mask": "32",
        "metric": "11",
        "network": "172.20.3.1",
        "nexthop_if": "FastEthernet0/0.100",
        "nexthop_ip": "194.0.0.2",
        "nexthop_vrf": "",
        "protocol": "O",
        "type": "",
        "uptime": "00:05:45",
        "vrf": "",
    },
    {
        "distance": "110",
        "mask": "32",
        "metric": "11",
        "network": "172.20.2.1",
        "nexthop_if": "FastEthernet0/0.100",
        "nexthop_ip": "194.0.0.2",
        "nexthop_vrf": "",
        "protocol": "O",
        "type": "",
        "uptime": "00:05:45",
        "vrf": "",
    },
    {
        "distance": "",
        "mask": "24",
        "metric": "",
        "network": "10.0.1.0",
        "nexthop_if": "Serial0/0",
        "nexthop_ip": "",
        "nexthop_vrf": "",
        "protocol": "C",
        "type": "",
        "uptime": "",
        "vrf": "",
    },
    {
        "distance": "90",
        "mask": "26",
        "metric": "2297856",
        "network": "10.0.5.0",
        "nexthop_if": "Serial0/0",
        "nexthop_ip": "10.0.1.2",
        "nexthop_vrf": "",
        "protocol": "D",
        "type": "",
        "uptime": "00:12:03",
        "vrf": "",
    },
    {
        "distance": "90",
        "mask": "26",
        "metric": "2297856",
        "network": "10.0.5.64",
        "nexthop_if": "Serial0/0",
        "nexthop_ip": "10.0.1.2",
        "nexthop_vrf": "",
        "protocol": "D",
        "type": "",
        "uptime": "00:12:03",
        "vrf": "",
    },
    {
        "distance": "90",
        "mask": "26",
        "metric": "2297856",
        "network": "10.0.5.128",
        "nexthop_if": "Serial0/0",
        "nexthop_ip": "10.0.1.2",
        "nexthop_vrf": "",
        "protocol": "D",
        "type": "",
        "uptime": "00:12:03",
        "vrf": "",
    },
    {
        "distance": "90",
        "mask": "27",
        "metric": "2297856",
        "network": "10.0.5.192",
        "nexthop_if": "Serial0/0",
        "nexthop_ip": "10.0.1.2",
        "nexthop_vrf": "",
        "protocol": "D",
        "type": "",
        "uptime": "00:12:03",
        "vrf": "",
    },
    {
        "distance": "200",
        "mask": "17",
        "metric": "0",
        "network": "11.1.0.0",
        "nexthop_if": "Null0",
        "nexthop_ip": "",
        "nexthop_vrf": "",
        "protocol": "B",
        "type": "",
        "uptime": "2w0d",
        "vrf": "",
    },
    {
        "distance": "",
        "mask": "16",
        "metric": "",
        "network": "12.0.0.0",
        "nexthop_if": "Null0",
        "nexthop_ip": "",
        "nexthop_vrf": "",
        "protocol": "S",
        "type": "",
        "uptime": "",
        "vrf": "",
    },
    {
        "distance": "",
        "mask": "17",
        "metric": "",
        "network": "13.14.128.0",
        "nexthop_if": "Null0",
        "nexthop_ip": "",
        "nexthop_vrf": "",
        "protocol": "O",
        "type": "",
        "uptime": "7w0d",
        "vrf": "",
    },
    {
        "distance": "90",
        "mask": "32",
        "metric": "2297856",
        "network": "192.168.0.1",
        "nexthop_if": "Serial0/0",
        "nexthop_ip": "10.0.1.2",
        "nexthop_vrf": "",
        "protocol": "D",
        "type": "",
        "uptime": "00:12:03",
        "vrf": "",
    },
    {
        "distance": "110",
        "mask": "29",
        "metric": "20",
        "network": "192.168.10.168",
        "nexthop_if": "TenGigabitEthernet7/4",
        "nexthop_ip": "7.7.7.170",
        "nexthop_vrf": "",
        "protocol": "O",
        "type": "E2",
        "uptime": "12:54:35",
        "vrf": "",
    },
    {
        "distance": "110",
        "mask": "23",
        "metric": "20",
        "network": "10.63.184.0",
        "nexthop_if": "TenGigabitEthernet1/15",
        "nexthop_ip": "10.62.4.29",
        "nexthop_vrf": "",
        "protocol": "O",
        "type": "E2",
        "uptime": "12:55:19",
        "vrf": "",
    },
    {
        "distance": "110",
        "mask": "23",
        "metric": "20",
        "network": "10.63.184.0",
        "nexthop_if": "TenGigabitEthernet1/16",
        "nexthop_ip": "10.62.3.29",
        "nexthop_vrf": "",
        "protocol": "O",
        "type": "E2",
        "uptime": "12:55:19",
        "vrf": "",
    },
    {
        "distance": "110",
        "mask": "27",
        "metric": "20",
        "network": "192.168.12.0",
        "nexthop_if": "Port-channel202",
        "nexthop_ip": "10.64.3.13",
        "nexthop_vrf": "",
        "protocol": "O",
        "type": "E2",
        "uptime": "12:54:36",
        "vrf": "",
    },
    {
        "distance": "110",
        "mask": "27",
        "metric": "20",
        "network": "192.168.12.0",
        "nexthop_if": "Port-channel201",
        "nexthop_ip": "10.64.1.9",
        "nexthop_vrf": "",
        "protocol": "O",
        "type": "E2",
        "uptime": "12:54:36",
        "vrf": "",
    },
    {
        "distance": "",
        "mask": "30",
        "metric": "",
        "network": "10.64.4.88",
        "nexthop_if": "Serial0/0/0:0",
        "nexthop_ip": "",
        "nexthop_vrf": "",
        "protocol": "C",
        "type": "",
        "uptime": "",
        "vrf": "",
    },
    {
        "distance": "110",
        "mask": "24",
        "metric": "20",
        "network": "10.6.234.0",
        "nexthop_if": "Serial0/0/0:0",
        "nexthop_ip": "10.64.4.90",
        "nexthop_vrf": "",
        "protocol": "O",
        "type": "E2",
        "uptime": "12:54:53",
        "vrf": "",
    },
    {
        "distance": "",
        "mask": "30",
        "metric": "",
        "network": "7.7.7.168",
        "nexthop_if": "TenGigabitEthernet7/4",
        "nexthop_ip": "",
        "nexthop_vrf": "",
        "protocol": "C",
        "type": "",
        "uptime": "",
        "vrf": "",
    },
    {
        "distance": "",
        "mask": "30",
        "metric": "",
        "network": "10.64.3.12",
        "nexthop_if": "Port-channel202",
        "nexthop_ip": "",
        "nexthop_vrf": "",
        "protocol": "C",
        "type": "",
        "uptime": "",
        "vrf": "",
    },
    {
        "distance": "",
        "mask": "30",
        "metric": "",
        "network": "10.64.1.8",
        "nexthop_if": "Port-channel201",
        "nexthop_ip": "",
        "nexthop_vrf": "",
        "protocol": "C",
        "type": "",
        "uptime": "",
        "vrf": "",
    },
    {
        "distance": "",
        "mask": "30",
        "metric": "",
        "network": "10.62.4.28",
        "nexthop_if": "TenGigabitEthernet1/15",
        "nexthop_ip": "",
        "nexthop_vrf": "",
        "protocol": "C",
        "type": "",
        "uptime": "",
        "vrf": "",
    },
    {
        "distance": "",
        "mask": "30",
        "metric": "",
        "network": "10.62.3.28",
        "nexthop_if": "TenGigabitEthernet1/16",
        "nexthop_ip": "",
        "nexthop_vrf": "",
        "protocol": "C",
        "type": "",
        "uptime": "",
        "vrf": "",
    },
    {
        "distance": "110",
        "mask": "24",
        "metric": "11",
        "network": "195.0.0.0",
        "nexthop_if": "FastEthernet0/0.100",
        "nexthop_ip": "194.0.0.2",
        "nexthop_vrf": "",
        "protocol": "O",
        "type": "IA",
        "uptime": "00:05:45",
        "vrf": "",
    },
    {
        "distance": "110",
        "mask": "0",
        "metric": "1",
        "network": "0.0.0.0",
        "nexthop_if": "FastEthernet0/0.100",
        "nexthop_ip": "194.0.0.2",
        "nexthop_vrf": "",
        "protocol": "O",
        "type": "E2",
        "uptime": "00:05:35",
        "vrf": "",
    },
    {
        "distance": "110",
        "mask": "8",
        "metric": "20",
        "network": "212.0.0.0",
        "nexthop_if": "FastEthernet0/0.100",
        "nexthop_ip": "194.0.0.2",
        "nexthop_vrf": "",
        "protocol": "O",
        "type": "E2",
        "uptime": "00:05:35",
        "vrf": "",
    },
    {
        "distance": "",
        "mask": "16",
        "metric": "",
        "network": "194.0.0.0",
        "nexthop_if": "FastEthernet0/0.100",
        "nexthop_ip": "",
        "nexthop_vrf": "",
        "protocol": "C",
        "type": "",
        "uptime": "",
        "vrf": "",
    },
]
