---
# HME-SWI-VSS01:
#   hostname: 10.10.20.1
#   groups: [ios]
# HME-NXOS-LEF01:
#   hostname: 10.10.20.21
#   groups: [nxos]
# HME-CSR-RTR01:
#   hostname: 10.10.20.22
#   groups: [iosxe]
HME-ASA-FW01:
  hostname: 10.10.20.23
  groups: [asa]
